version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: idkidonthaveone
      MONGODB_URI: mongodb+srv://Youssef:youssef23032004@cluster0.e6x8ran.mongodb.net/ProjetClasse?retryWrites=true&w=majority&appName=Cluster0
      MONGODB_DB: ProjetClasse
      JWT_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
      HOSTNAME: 0.0.0.0
      PORT: 3000
    restart: unless-stopped
    networks:
      - school-network

networks:
  school-network:
    driver: bridge
