// app/layout.jsx
import '@/app/globals.css'; // Add this import

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) { // Remove extra curly brace here
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
} 